name: Delopy hello world
on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: install rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: test
        uses: actions/checkout@v5
      - run: |
          cargo test
          cargo run
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build
        uses: actions/checkout@v5
      - run: cargo build
